owner: AnimalEquality
repo: upptime

sites:
  - name: US
    url: https://animalequality.org/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: COMMITMENT

  - name: BR
    url: https://animalequality.org.br/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: VISÃO

  - name: DE
    url: https://animalequality.de/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: "ist eine internationale"

  - name: ES
    url: https://igualdadanimal.org/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: VISIÓN

  - name: IN
    url: https://animalequality.in/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: VISION

  - name: IT
    url: https://animalequality.it/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: animali

  - name: MX
    url: https://igualdadanimal.org/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: VISIÓN

  - name: UK
    url: https://animalequality.org.uk/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: VISION

  - name: Investigations US
    url: https://animalequality.org/action/babyhell
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: BABYBEL

  - name: Investigations BR
    url: https://animalequality.org.br/participe/stopfoiegras
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: gras

  - name: Investigations DE
    url: https://animalequality.de/kampagnen/gadhimai
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Massaker

  - name: Investigations ES
    url: https://igualdadanimal.org/actua/mataderos
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: firmar

  - name: Investigations IN
    url: https://animalequality.in/action/prosecute-buffalo-abusers
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: routinely

  - name: Investigations IT
    url: https://animalequality.it/agisci/supermercati-contro-gabbie
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: gabbia

  - name: Investigations MX
    url: https://igualdadanimal.mx/actua/mision-sin-jaulas
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: MALTRATO

  - name: Investigations UK
    url: https://animalequality.org.uk/act/ban-force-feeding
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: importation

    ## Loveveg
  - name: LoveVeg US
    url: https://loveveg.com/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Enjoy

  - name: LoveVeg BR
    url: https://loveveg.com.br
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Love Veg

  - name: LoveVeg DE
    url: https://loveveg.de
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Entdecke

  - name: LoveVeg ES
    url: https://es.loveveg.com
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Razones

  - name: LoveVeg IN
    url: https://loveveg.in
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Enjoy

  - name: LoveVeg IT
    url: https://it.loveveg.com/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: buono

  - name: LoveVeg MX
    url: https://loveveg.mx/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Disfruta

  - name: LoveVeg UK
    url: https://loveveg.uk/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: Enjoy

  - name: Cygne
    url: $CYGNE_URL
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: markets

  - name: Corporate Progress
    url: https://corporatesocialresponsibility.us/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: responsibility

  - name: Etalon
    url: $ETALON_URL
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: translation

  - name: VoiceLessFriends
    url: https://voicelessfriends.org/
    __dangerous__body_degraded: archive.org
    __dangerous__body_down_if_text_missing: clothes

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.animalequality.org
  baseUrl: /upptime
  logoUrl: https://static.animalequality.org/logo/ae/us/default.svg
  name: AnimalEquality websites status
  introTitle: ''
  introMessage: ''
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
