on:
  issues:
    types: [opened, closed]
jobs:
  release:
    name: Notify MM
    runs-on: ubuntu-20.04
    steps:
      - name: Create the Mattermost Message
        env:
          NUM: ${{ github.event.issue.number }}
        run: |
          echo "{\"text\":\"Uptime event: ${NUM}:\"}" > mattermost.json
      - name: Mattermost
        uses: mattermost/action-mattermost-notify@1.1.0
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
